### ISSUE TITLE
Cleverbot Webservice Link 404's

### ISSUE THREAD

**Issue by NeighbourJim** [pierredavidbelanger/chatter-bot-api#35]
Looks like they've changed the webservice link for Cleverbot again, its now returning a 404 error.

Any idea what the new one is?

**Comment by Skerberus** [comment]
http://www.cleverbot.com/webservicemin?uc=321

**Comment by pierredavidbelanger** [comment]
Indeed, I get the same error.

**Comment by TheEpTic** [comment]
I'm getting the same error.

**Comment by Brawl345** [comment]
Yes everyone gets the same error, please stop commenting this.

**Comment by NeighbourJim** [comment]
The link Skerberus posted fixes it.

**Comment by Brawl345** [comment]
Yes but it works. E.g. for PHP replace the URL here: https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/php/chatterbotapi.php#L39

**Comment by TheEpTic** [comment]
I'm using the Java version 🙄

**Comment by Brawl345** [comment]
It was an example. Why should I spoon-feed you? Change it in the java file, done.

**Comment by pierredavidbelanger** [comment]
@Brawl345 I like people commenting issues. It usually help me fixing things. If you don't want to get notified by each comment, you can unsubscribe from this threads.

That being said, indeed, you are right, the "me too" comments are usually redundant, one is better "add reaction" to an existing comment instead :)

@NeighbourJim I will reopen. This issue is not fixed on this projet (and for the majority of its users). @Skerberus post a good work around though.

@Brawl345 No one is asking YOU to spoon feed anyone :)

**Comment by TheEpTic** [comment]
@Brawl345 I never once requested a spoon fed response. It would be nice you could drop this rude attitude, as nothing gets resolved with rudeness.

@pierredavidbelanger Appreciate you re-opening considering a URL doesn't seem to fix it for everyone. I made a small PR to change the URL on the Java application but it might be worth closing since it doesn't actually fix it for everyone.

**Comment by pierredavidbelanger** [comment]
Thanks to @TheEpTic 's PR #36 the Java version is now fixed.

And version [1.4.3](https://github.com/pierredavidbelanger/chatter-bot-api#maven) will soon appear on [Maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22ca.pjer%22%20AND%20a%3A%22chatter-bot-api%22).

**Comment by pierredavidbelanger** [comment]
Fixed also the php, python and .net version.

As always though, the .net version was only tested with mono:
```shell
$ mono --version
Mono JIT compiler version 4.0.5 ((detached/1d8d582 Tue Oct 20 15:15:33 EDT 2015)
```

And, as @TheEpTic said, this URL hack may not work for everyone. I suggest everyone to update their code to the latest version and try.

I will close this issue now, from my perspective, everything is working.

Thank you for your help.
