### ISSUE TITLE
404 on Cleverbot

### ISSUE THREAD

**Issue by magalvao** [pierredavidbelanger/chatter-bot-api#9]
The PHP example is not working on my machine. On the PHP error log:

[Wed Jun 03 16:33:37 2015] [error] PHP Warning:  fopen(http://www.cleverbot.com/webservicemin): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found\r\n in files/cleverbot/chatterbotapi.php on line 255
[Wed Jun 03 16:33:37 2015] [error] PHP Warning:  stream_get_contents() expects parameter 1 to be resource, boolean given in files/cleverbot/chatterbotapi.php on line 256
[Wed Jun 03 16:33:37 2015] [error] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in files/cleverbot/chatterbotapi.php on line 257

There is something wrong on the Cleverbot side?

**Comment by pierredavidbelanger** [comment]
You are right, 
even in the browser, http://www.cleverbot.com/webservicemin is giving me a 404.

Either CleverBot is down momentarily, or they changed their WebService so we can no longer use it.

**Comment by PhoenixICE** [comment]
http://www.cleverbot.com/webservicemin is giving me DENIED +3000_cbfull atm hmm...

**Comment by robomaeyhem** [comment]
Looks like Jabberwacky is also returning 404 via http://www.existor.com/webservicemin

**Comment by sbwMikael** [comment]
That ends my confusion, at least. I stumbled across this project earlier today, and had started work on integrating it into a game, but couldn't understand why I wasn't getting any bot responses. I'll keep coming back for updates, but I hope this is only a temporary state of affairs.

**Comment by pierredavidbelanger** [comment]
I will take a look at this problem today.

**Comment by t3zla** [comment]
Any update on this? Is this api done?

**Comment by pierredavidbelanger** [comment]
Yeah, their web service was changed.
I will need to reverse engineer the flow once again.
This will take some time.

**Comment by modsfabio** [comment]
When you visit the cleverbot.com website and after that http://www.cleverbot.com/webservicemin isn't returning 404 anymore. But "DENIED +3000_cbfull" not sure whats this about...
Any Idea?

**Comment by modsfabio** [comment]
When is this going to be fixed? :(

**Comment by wardellchandler** [comment]
@pierredavidbelanger You might want to look into this. I have a bot that uses Hangouts, and I was using a cleverbot api for it. One of my forks came up with a fix for the api I was uses; they saved the cookies and it worked. Check out this commit here:

https://github.com/wardellchandler/HangoutsBot/commit/42d90010aa232768320de9b1c3a47ff0cc740be0

**Comment by pierredavidbelanger** [comment]
@wardellchandler 
Nice, I will try this as soon as I find a couple minutes.

**Comment by modsfabio** [comment]
It worked! Awesome :)

**Comment by modsfabio** [comment]
Pull request. Maybe not beautiful but works :) https://github.com/pierredavidbelanger/chatter-bot-api/pull/10

**Comment by robomaeyhem** [comment]
Any word on a Java solution?

**Comment by pierredavidbelanger** [comment]
I have a working fix for the Java version.
I will push it (in Github and Maven Central) this evening (around 20h, this is in about 3 or 4 hours).

**Comment by sbwMikael** [comment]
Thanks very much for the updates

**Comment by pierredavidbelanger** [comment]
Its [deployed](https://oss.sonatype.org/content/repositories/releases/ca/pjer/chatter-bot-api/1.3.3/) on maven. It should be [visible](https://maven-repository.com/artifact/ca.pjer/chatter-bot-api) anytime soon.

**Comment by robomaeyhem** [comment]
Jabberwacky comes back as an empty string every time in Java it seems

**Comment by remiscarlet** [comment]
Any information on the python side of things being updated?

**Comment by pierredavidbelanger** [comment]
I am sorry guys, I did not had the time to really fix every port of the library.
I can not give you an ETA either.

Feel free to contribute :)

The fix is really simple: 

1) The Session object now have a new variable to hold the cookies
https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/Cleverbot.java#L40

2) When a new Session is created, the variable is initialized
https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/Cleverbot.java#L50

3) And a GET is issued to Cleverbot the get all the cookies:
https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/Cleverbot.java#L52

4) The request method in the Utils class, now take care of reading the cookie from the response:
https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/Utils.java#L81

5) Then, when the think method is called, we issue a request using the Session cookies:
https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/Cleverbot.java#L66

6) The request method in the Utils class also take care of sending cookies:
https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/Utils.java#L63

**Comment by sbwMikael** [comment]
Seems something has changed again? Or else I'm experiencing localised troubles. But as of an hour ago or so, I was initially getting just ads for something called "Clevertweet" and then blank responses.

I think I'll bow out now though. I just wanted to add botchat as a feature for visitors to our game server during slow periods, but it's not something we can't live without. Thanks for the project

**Comment by pierredavidbelanger** [comment]
The [simple PHP version](https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/php/chatterbotapi.php) is also fixed.

**Comment by pierredavidbelanger** [comment]
Also fixed in the [python version](https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/python/chatterbotapi.py).

**Comment by robomaeyhem** [comment]
Jabberwacky still looks like it's returning an empty String in the Java version, regardless of what is inputted

**Comment by pierredavidbelanger** [comment]
Also fixed in the .NET version thanks to @KSemenenko 's [nice Pull Request](https://github.com/pierredavidbelanger/chatter-bot-api/pull/11).
He bump the .NET requirement from 2.0 to 4.5 though.
I hope everyone using the .NET version is ok with this.

**Comment by iObsidian** [comment]
Java is still not working

**Comment by pierredavidbelanger** [comment]
@iObsidian I just tried the [example code](https://github.com/pierredavidbelanger/chatter-bot-api#java) with the [latest maven](https://github.com/pierredavidbelanger/chatter-bot-api#maven) version and it worked.

Ensure you are using the latest version, and If it still does not work for you, please open a new issue with a description of what you are doing, what you expect, what you see instead and ideally a stack trace if you have one.

**Comment by iObsidian** [comment]
Hey Pierre, thanks for answering! Pandora bots works while clever bot doesn't. Thanks for your time :)
